@startuml
(*) -->  "Készenlét" as A1
A1 -->[Bankkártya behelyezés] "Bankkártya elvétele" as A2
A2 -->[PIN kód kérése] "Ellenőrzés" as A3
A3 -->if "Jó a PIN kód?" then
    -->[Nem] if "Hanyadik próbálkozás?" then 
        --> [<3] A3
        else
        -->[Bankkártya elvétele] A1
        endif
    else
    -->[Igen] "Főmenü" as A4
    endif
    A4 -->[Opciók feldobása] "Opciók" as A5
    A5 --> "Egyenleg lekérdezés" as A6
    A6 -->[Gomb megnyomása] "Egyenleg kiadása" as A7
    A7 -->"Bankkártya kiadása" as A8
    A8 --> A1

A1 --> (*)
@enduml